/home/dark/actual/bank-sync.log /home/dark/actual-tools/*.log {
    daily
    rotate 14
    maxsize 5M
    su dark dark
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    create 0600 dark dark
}
